language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://nathandeamer.pact.dius.com.au
  # PACT_BROKER_TOKEN is encrypted below
  - secure: aEt7fS8iQwtTOd2t2r6BfroLU0TfNlG3lKaDDziSjJsK8mU+nBB7BoUItNwiwmwZi2LKFPN8V3BohuVq0E2Mw65xJZBMW4S5FRRr+rB8t+NtVz2+VmgiueqB/ss78BYXb1UvZMOpvlSmCmLSj0UJX65IqkwMoMb6aGmYn9tWs46NVqtNLouPHNYkLng1Aa18Ugy1obxrqFb0u5/BgjAq/K9/5xpi3Pd1ix55qsqZicqgnhQtOrZEIqFS7x+9I4+p0AI/x+2K/mHOoGe9WWkr/qCrEgVGWspUqREdIyanviCxixu+d5J/SoK1zAJpzwvpVJfC9Br/BJNq9DH28pFkP/gJXn85QEnl0F1NczVRILP2OnJUTri+NPvdEuAbishdiiI5dRWX1q/S2U3IZfx6RtxjUHINh4xKZDlrjRurC8SWe4iGzhI1ZEZVw7o8Scr93+gZsy4w9tqU2RpB2HGaXuZ5r/ETFVEzz+gmgTu09sWufB+2F7gbKTlqUlo3v7Ev7ZRKNXxgAI1VOXqipEzLgWdMS1ubaBL9e6T8PK8GaYz9ToET+WwjpsdY5xG42tVr7mEQCYAWYrDEBLlNwUgC1jxkAWlAdY135gDKzbckzuW0AiD2WaWLK49SWwoU3UJpfOUo1TZ2hriFn73Y0BEB86jsDIgfqQszoJVjsXwcZy4=
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
