language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://nathandeamer.pact.dius.com.au
  # PACT_BROKER_TOKEN is encrypted below
  - secure: klLQuTIyHkyT7lMs9w00IwyZlN/X+l6FpmAY2JoYDl0w5nhue0EtLrc2VA41P8rnRHdP4pL9yG07tEZzEaD9WMVGqAOX3fntSpnZvHR8bAogiE7ykhAbCUDGXm8p3y4WmLHAOdzsmuSUODy420l7vcQdRm9YBFlvNc2WTgOVt3MWkSWIITetySQgvN4doNIbX+fYaXKmnt3TVIs60F0NzgHuP2Fez+67ixq9Kt+9gXtMB9I3EPdRvCPBQf4PVsaFAJaHKa26zd6nWcu2u3KsI3vMwcbCg4oIiNnEblAH2deA5uC1qeumN3i+S1qA98rfu8oUtHKWuq6sVtF4xT8gmlwLMN6q2hlCHy83dmQe7V7VD1aTdgaFsvtw4M40kfCHWjVn4k0Y/S5zAUcG76+Z7KWOwXO89ckxiCtRlKzG15+FFJ4PhmlSUM+/GtLdJV36fYpIZVHD76v5K4+/mMYIQJzvzLjVgilV/6zLuJ5TcS2+xvQC/cQHmuQ3VDpvMBLyZ8MKT8Ie6ZEAdk7AFeIw4EmQR5FgjuABZlo+sogsyXskih43KQQ3Tbdtpvg1eHXb+82ESSeGAInqEc5vXiG6IvvBcHu7ZP/cKdkOz7xkcxc2CWQlsmhswZJN2RkYYrTm6RRitVyOyccyOrMLeZoUoDOluOUIJq1wPAGIxLdNaX0=
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
